editPin -pin clk -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin reset -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_0[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_0[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_0[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_0[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_0[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_0[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_0[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_0[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_0[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_1[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_1[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_1[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_1[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_1[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_1[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_1[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_1[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_1[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_2[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_2[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_2[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_2[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_2[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_2[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_2[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_2[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_2[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_3[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_3[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_3[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_3[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_3[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_3[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_3[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_3[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_3[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_4[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_4[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_4[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_4[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_4[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_4[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_4[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_4[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_4[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_5[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_5[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_5[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_5[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_5[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_5[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_5[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_5[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_5[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_6[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_6[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_6[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_6[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_6[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_6[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_6[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_6[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_6[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_7[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_7[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_7[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_7[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_7[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_7[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_7[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_7[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_7[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_8[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_8[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_8[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_8[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_8[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_8[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_8[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_8[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_8[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_9[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_9[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_9[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_9[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_9[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_9[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_9[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_9[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_9[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_10[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_10[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_10[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_10[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_10[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_10[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_10[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_10[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_10[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_11[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_11[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_11[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_11[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_11[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_11[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_11[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_11[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_11[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_12[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_12[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_12[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_12[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_12[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_12[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_12[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_12[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_12[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_13[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_13[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_13[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_13[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_13[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_13[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_13[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_13[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_13[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_14[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_14[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_14[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_14[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_14[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_14[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_14[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_14[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_14[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_15[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_15[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_15[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_15[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_15[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_15[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_15[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_15[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {y_15[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_0[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_0[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_0[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_0[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_0[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_0[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_0[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_0[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_0[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_1[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_1[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_1[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_1[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_1[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_1[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_1[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_1[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_1[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_2[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_2[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_2[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_2[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_2[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_2[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_2[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_2[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_2[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_3[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_3[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_3[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_3[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_3[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_3[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_3[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_3[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_3[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_4[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_4[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_4[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_4[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_4[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_4[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_4[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_4[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_4[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_5[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_5[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_5[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_5[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_5[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_5[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_5[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_5[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_5[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_6[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_6[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_6[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_6[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_6[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_6[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_6[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_6[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_6[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_7[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_7[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_7[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_7[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_7[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_7[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_7[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_7[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_7[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_8[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_8[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_8[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_8[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_8[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_8[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_8[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_8[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_8[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_9[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_9[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_9[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_9[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_9[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_9[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_9[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_9[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_9[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_10[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_10[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_10[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_10[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_10[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_10[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_10[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_10[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_10[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_11[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_11[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_11[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_11[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_11[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_11[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_11[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_11[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_11[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_12[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_12[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_12[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_12[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_12[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_12[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_12[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_12[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_12[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_13[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_13[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_13[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_13[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_13[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_13[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_13[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_13[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_13[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_14[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_14[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_14[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_14[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_14[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_14[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_14[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_14[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_14[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_15[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_15[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_15[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_15[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_15[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_15[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_15[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_15[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {x_15[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin main_enable -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin done -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {col[15]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {col[14]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {col[13]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {col[12]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {col[11]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {col[10]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {col[9]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {col[8]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {col[7]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {col[6]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {col[5]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {col[4]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {col[3]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {col[2]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {col[1]} -layer 2 -fixedPin -assign {20 0} -side TOP
editPin -pin {col[0]} -layer 2 -fixedPin -assign {20 0} -side TOP
