# ####################################################################

#  Created by Genus(TM) Synthesis Solution 17.11-s014_1 on Fri Dec 14 11:35:20 CET 2018

# ####################################################################

set sdc_version 2.0

set_units -capacitance 1000.0fF
set_units -time 1000.0ps

# Set the current design
current_design top_level

create_clock -name "clk" -add -period 40.0 -waveform {0.0 20.0} [get_ports clk]
set_load -pin_load 1.0 [get_ports done]
set_load -pin_load 1.0 [get_ports {col[15]}]
set_load -pin_load 1.0 [get_ports {col[14]}]
set_load -pin_load 1.0 [get_ports {col[13]}]
set_load -pin_load 1.0 [get_ports {col[12]}]
set_load -pin_load 1.0 [get_ports {col[11]}]
set_load -pin_load 1.0 [get_ports {col[10]}]
set_load -pin_load 1.0 [get_ports {col[9]}]
set_load -pin_load 1.0 [get_ports {col[8]}]
set_load -pin_load 1.0 [get_ports {col[7]}]
set_load -pin_load 1.0 [get_ports {col[6]}]
set_load -pin_load 1.0 [get_ports {col[5]}]
set_load -pin_load 1.0 [get_ports {col[4]}]
set_load -pin_load 1.0 [get_ports {col[3]}]
set_load -pin_load 1.0 [get_ports {col[2]}]
set_load -pin_load 1.0 [get_ports {col[1]}]
set_load -pin_load 1.0 [get_ports {col[0]}]
set_clock_gating_check -setup 0.0 
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports clk]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports reset]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_0[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_0[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_0[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_0[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_0[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_0[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_0[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_0[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_0[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_1[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_1[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_1[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_1[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_1[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_1[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_1[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_1[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_1[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_2[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_2[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_2[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_2[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_2[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_2[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_2[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_2[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_2[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_3[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_3[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_3[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_3[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_3[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_3[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_3[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_3[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_3[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_4[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_4[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_4[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_4[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_4[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_4[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_4[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_4[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_4[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_5[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_5[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_5[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_5[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_5[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_5[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_5[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_5[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_5[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_6[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_6[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_6[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_6[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_6[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_6[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_6[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_6[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_6[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_7[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_7[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_7[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_7[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_7[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_7[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_7[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_7[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_7[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_8[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_8[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_8[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_8[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_8[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_8[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_8[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_8[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_8[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_9[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_9[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_9[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_9[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_9[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_9[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_9[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_9[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_9[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_10[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_10[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_10[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_10[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_10[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_10[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_10[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_10[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_10[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_11[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_11[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_11[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_11[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_11[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_11[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_11[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_11[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_11[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_12[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_12[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_12[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_12[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_12[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_12[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_12[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_12[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_12[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_13[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_13[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_13[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_13[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_13[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_13[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_13[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_13[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_13[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_14[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_14[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_14[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_14[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_14[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_14[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_14[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_14[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_14[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_15[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_15[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_15[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_15[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_15[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_15[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_15[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_15[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {y_15[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_0[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_0[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_0[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_0[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_0[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_0[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_0[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_0[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_0[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_1[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_1[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_1[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_1[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_1[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_1[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_1[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_1[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_1[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_2[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_2[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_2[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_2[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_2[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_2[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_2[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_2[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_2[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_3[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_3[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_3[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_3[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_3[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_3[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_3[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_3[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_3[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_4[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_4[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_4[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_4[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_4[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_4[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_4[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_4[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_4[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_5[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_5[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_5[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_5[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_5[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_5[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_5[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_5[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_5[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_6[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_6[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_6[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_6[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_6[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_6[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_6[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_6[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_6[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_7[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_7[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_7[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_7[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_7[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_7[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_7[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_7[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_7[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_8[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_8[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_8[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_8[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_8[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_8[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_8[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_8[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_8[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_9[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_9[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_9[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_9[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_9[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_9[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_9[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_9[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_9[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_10[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_10[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_10[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_10[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_10[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_10[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_10[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_10[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_10[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_11[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_11[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_11[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_11[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_11[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_11[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_11[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_11[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_11[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_12[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_12[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_12[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_12[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_12[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_12[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_12[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_12[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_12[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_13[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_13[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_13[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_13[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_13[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_13[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_13[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_13[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_13[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_14[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_14[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_14[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_14[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_14[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_14[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_14[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_14[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_14[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_15[8]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_15[7]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_15[6]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_15[5]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_15[4]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_15[3]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_15[2]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_15[1]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports {x_15[0]}]
set_input_delay -clock [get_clocks clk] -add_delay 0.2 [get_ports main_enable]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports done]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {col[15]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {col[14]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {col[13]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {col[12]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {col[11]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {col[10]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {col[9]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {col[8]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {col[7]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {col[6]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {col[5]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {col[4]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {col[3]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {col[2]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {col[1]}]
set_output_delay -clock [get_clocks clk] -add_delay 0.5 [get_ports {col[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports clk]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports reset]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_0[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_0[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_0[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_0[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_0[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_0[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_0[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_0[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_0[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_1[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_1[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_1[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_1[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_1[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_1[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_1[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_1[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_1[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_2[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_2[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_2[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_2[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_2[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_2[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_2[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_2[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_2[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_3[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_3[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_3[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_3[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_3[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_3[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_3[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_3[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_3[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_4[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_4[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_4[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_4[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_4[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_4[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_4[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_4[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_4[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_5[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_5[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_5[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_5[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_5[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_5[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_5[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_5[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_5[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_6[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_6[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_6[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_6[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_6[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_6[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_6[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_6[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_6[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_7[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_7[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_7[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_7[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_7[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_7[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_7[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_7[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_7[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_8[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_8[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_8[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_8[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_8[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_8[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_8[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_8[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_8[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_9[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_9[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_9[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_9[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_9[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_9[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_9[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_9[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_9[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_10[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_10[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_10[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_10[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_10[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_10[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_10[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_10[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_10[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_11[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_11[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_11[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_11[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_11[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_11[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_11[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_11[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_11[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_12[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_12[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_12[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_12[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_12[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_12[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_12[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_12[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_12[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_13[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_13[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_13[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_13[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_13[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_13[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_13[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_13[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_13[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_14[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_14[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_14[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_14[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_14[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_14[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_14[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_14[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_14[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_15[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_15[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_15[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_15[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_15[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_15[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_15[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_15[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {y_15[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_0[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_0[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_0[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_0[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_0[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_0[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_0[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_0[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_0[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_1[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_1[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_1[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_1[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_1[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_1[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_1[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_1[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_1[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_2[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_2[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_2[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_2[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_2[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_2[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_2[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_2[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_2[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_3[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_3[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_3[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_3[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_3[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_3[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_3[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_3[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_3[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_4[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_4[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_4[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_4[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_4[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_4[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_4[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_4[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_4[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_5[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_5[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_5[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_5[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_5[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_5[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_5[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_5[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_5[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_6[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_6[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_6[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_6[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_6[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_6[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_6[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_6[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_6[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_7[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_7[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_7[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_7[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_7[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_7[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_7[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_7[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_7[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_8[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_8[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_8[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_8[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_8[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_8[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_8[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_8[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_8[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_9[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_9[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_9[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_9[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_9[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_9[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_9[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_9[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_9[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_10[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_10[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_10[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_10[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_10[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_10[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_10[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_10[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_10[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_11[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_11[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_11[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_11[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_11[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_11[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_11[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_11[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_11[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_12[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_12[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_12[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_12[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_12[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_12[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_12[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_12[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_12[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_13[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_13[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_13[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_13[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_13[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_13[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_13[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_13[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_13[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_14[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_14[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_14[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_14[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_14[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_14[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_14[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_14[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_14[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_15[8]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_15[7]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_15[6]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_15[5]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_15[4]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_15[3]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_15[2]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_15[1]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports {x_15[0]}]
set_driving_cell -lib_cell INVD0BWP7T -library tcb018gbwp7twc -pin "ZN" [get_ports main_enable]
set_wire_load_mode "segmented"
set_wire_load_selection_group "WireAreaForZero" -library "tcb018gbwp7twc"
set_dont_use [get_lib_cells tcb018gbwp7twc/BHDBWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GAN2D1BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GAN2D2BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GAOI21D1BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GAOI21D2BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GAOI22D1BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GBUFFD1BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GBUFFD2BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GBUFFD3BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GBUFFD8BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GDCAP10BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GDCAP2BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GDCAP3BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GDCAP4BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GDCAPBWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GDFCNQD1BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GDFQD1BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GFILL10BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GFILL2BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GFILL3BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GFILL4BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GFILLBWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GINVD1BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GINVD2BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GINVD3BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GINVD8BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GMUX2D1BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GMUX2D2BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GMUX2ND1BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GMUX2ND2BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GND2D1BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GND2D2BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GND2D3BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GND3D1BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GND3D2BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GNR2D1BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GNR2D2BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GNR3D1BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GNR3D2BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GOAI21D1BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GOAI21D2BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GOR2D1BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GOR2D2BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GSDFCNQD1BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GTIEHBWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GTIELBWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GXNR2D1BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GXNR2D2BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GXOR2D1BWP7T]
set_dont_use [get_lib_cells tcb018gbwp7twc/GXOR2D2BWP7T]
