read_hdl -vhdl {collision.vhd}
read_hdl -vhdl {counter_one.vhd}
read_hdl -vhdl {counter_two.vhd}
read_hdl -vhdl {top_level.vhd}
read_hdl -vhdl {collision-behaviour.vhd}
read_hdl -vhdl {counter_one-behaviour_counter_one.vhd}
read_hdl -vhdl {counter_two-behaviour.vhd}
read_hdl -vhdl {top_level-behaviour.vhd}
read_hdl -vhdl {counter_two_behaviour_counter_two_cfg.vhd}
read_hdl -vhdl {counter_one_behaviour_counter_one_cfg.vhd}
read_hdl -vhdl {collision_behaviour_collision_cfg.vhd}
read_hdl -vhdl {top_level_behaviour_top_level_cfg.vhd}
